version: '3.8'

services:
  # 1. Base de datos para el AuthService (.NET)
  restaurante-db:
    image: postgres:15-alpine
    container_name: restaurante-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: restaurante_auth_db
    ports:
      - "5432:5432"
    volumes:
      - restaurante_db_data:/var/lib/postgresql/data

  # 2. Base de datos para Server Admin (Node.js)
  mongo-db:
    image: mongo:latest
    container_name: restaurante-server-admin-mongo
    ports:
      - "27017:27017"
    volumes:
      - restaurante_mongo_data:/data/db

  # 3. Microservicio de Autenticacion (.NET)
  restaurante-auth-service:
    build:
      context: ./Restaurante-Auth-Service/Restaurante.AuthService
      dockerfile: Dockerfile
    container_name: restaurante-auth-service
    ports:
      - "5065:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__PostgresConnection=Host=restaurante-db;Database=restaurante_auth_db;Username=postgres;Password=admin
      - Jwt__Key=Restaurante_Super_Secret_Key_2026_DotNet8
      - Jwt__Issuer=auth-service
      - Jwt__Audience=restaurante-app
      - SeedSettings__AdminPassword=Admin1234!
    depends_on:
      - restaurante-db

  # 4. API de Administracion (Node.js)
  restaurante-server-admin:
    build:
      context: ./Restaurante-Server-Admin
      dockerfile: Dockerfile
    container_name: restaurante-server-admin
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - URI_MONGODB=mongodb://mongo-db:27017/restauranteAdmin
      - JWT_SECRET=Restaurante_Super_Secret_Key_2026_DotNet8
    depends_on:
      - mongo-db

  # 5. Cliente Admin (React/Vite)
  restaurante-client-admin:
    build:
      context: ./Restaurante-Client-Admin
      dockerfile: Dockerfile
      args:
        - VITE_AUTH_URL=http://localhost:5065/api/v1
        - VITE_ADMIN_URL=http://localhost:3001/restaurant/v1
    container_name: restaurante-client-admin
    ports:
      - "5173:80"
    depends_on:
      - restaurante-auth-service
      - restaurante-server-admin

volumes:
  restaurante_db_data:
  restaurante_mongo_data:
